### ISSUE TITLE
Resource management for ESP32 apps

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-firmware-esp32#110]
The launcher menu still lacks icons for the ESP32 native apps. Also ESP32 apps might require additional resources, so we should think about storing those somewhere.

The main ESP32 app binary is installed to appfs with a filename equal to it's hatchery slug.

Resources will be placed in /internal/apps/esp32/example_slug_name/

The icon shall be a 32x32 PNG image named icon.png in the resources folder

**Comment by Pwuts** [comment]
Looks like it works now :)
