### ISSUE TITLE
Inconsistency between error message and app name for Python

### ISSUE THREAD

**Issue by smunaut** [badgeteam/mch2022-firmware-esp32#137]
If python isn't available, the error message refers to it as "BadgePython", but in the Hatchery it's named "Python" and this confused some people so it'd be better to make them match.

Question is do we change the error message to say "Python", or update the Hatchery to say "BadgePython" ?

@renzenicolai opinion ?

**Comment by renzenicolai** [comment]
Change to python for now and eventually change back once hatchery can do that

**Comment by a2800276** [comment]
There's also "Micropython" ... I think we need to make sure we are more clear when documenting...

**Comment by renzenicolai** [comment]
Some clarification:

MicroPython is the upstream project. BadgePython is the name of our project. BadgePython is an extension of MicroPython adding all kinds of badge related features such as a graphics stack and drivers/abstractions for most of the peripherals found on the supported badges.

On the hatchery apps currently can't have a title different from their slug name, the slug for the BadgePython app for the MCH2022 badge is "python" as it's the default python implementation for the MCH2022 badge. Maybe a future version of the hatchery will fix this 😄 

For now the error message has been changed to "Python is not installed\n\nPlease install 'Python'\nusing the Hatchery under\n'ESP32 native binaries\\Utility".
