### ISSUE TITLE
(Web)USB FSLS times out for large folders

### ISSUE THREAD

**Issue by Pwuts** [badgeteam/mch2022-firmware-esp32#146]
The USB FSLS command seems to either fail or respond very slowly when listing large folders. The more items in a folder, the higher the chance of a time-out.

Experienced/tested with https://mch2022-badge-webusb.vercel.app. Try `/internal/apps/python/citycontrol` on the MCH2022 badge for example.

**Comment by renzenicolai** [comment]
Interesting, try to dump all communication into the console, I bet the badge spits out some ascii text with a crashlog if it stops responding...

I will ask details via Tg.

**Comment by Pwuts** [comment]
This is a good use case for a "dump everything" switch in the settings :)

**Comment by Pwuts** [comment]
Looks like this is an issue with the user agent. Works fine with devtools closed, starts faltering with devtools open. Closing for now.
