### ISSUE TITLE
[WebUSB] Start BadgePython with given app

### ISSUE THREAD

**Issue by Pwuts** [badgeteam/mch2022-firmware-esp32#147]
The APPX command currently doesn't support starting e.g. BadgePython into a specific app. This would be a great addition and allow cool UX in https://github.com/badgeteam/mch2022-webusb-site :)

**Comment by renzenicolai** [comment]
Added to my to-do list, will be added soon 😄

**Comment by renzenicolai** [comment]
Fixed in 2.0.6
