### ISSUE TITLE
Launcher firmware: FPGA bitstream download function

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-firmware-esp32#5]

**Comment by smunaut** [comment]
JFYI, I pushed an implementation in https://github.com/badgeteam/mch2022-firmware-esp32/tree/tnt/fpga-download based off the incomplete implementation in the `fpga-bitstream-download` branch.

Definitely not meant as anything final but just something to allow easier FPGA dev while waiting for final proper implementation.
