### ISSUE TITLE
Launcher firmware: WiFi setup

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-firmware-esp32#8]
- We need working WiFI setup
   - Scan for networks AND manual SSID entry
   - Entering a password AND connecting to open wifi networks
   
Bonus points if we can store the security type of the network that is configured so that we don't connect to an open network with the same name as the configured secure network for example.

**Comment by robotman2412** [comment]
I've done some initial work on getting the WiFi connection to work.
You can now call `wifi_init` when already initialised and it won't crash the ESP32.

[Relevant commit](https://github.com/badgeteam/mch2022-firmware-esp32/commit/6bde17e133727bda42a4f0a39cc32594df35a431)
