### ISSUE TITLE
WiFi setup: security field stays blank

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-firmware-esp32#98]
After configuring wifi the security field in the "Show current settings" menu stays blank.

**Comment by robotman2412** [comment]
https://github.com/badgeteam/mch2022-firmware-esp32/pull/99

**Comment by robotman2412** [comment]
![IMG_20220624_104851825.jpg](https://user-images.githubusercontent.com/25562445/175500047-eff964b0-fc63-4e02-a0f7-2ca6805ba36d.jpg)
